language: node_js
install:
  - npm install -g codecov
node_js:
  - "node"
  - "lts/*"
cache:
  directories:
    - "node_modules"
services:
  - docker
script:
  - yarn test
  - codecov
  - yarn docker-build
  - yarn docker-run
  - sleep 3
  - yarn testRunningServer
  - codecov
