language: node_js
node_js:
  - "node"
  - "lts/*"
cache:
  directories:
    - "node_modules"
services:
  - docker
script:
  - yarn test
  - yarn docker-build
  - yarn docker-run
  - sleep 3
  - yarn testRunningServer
